### ISSUE TITLE
Adding to a Custom Template

### ISSUE THREAD

**Issue by sully1107** [JiveDig/acf-tabbed-content#3]
Hi,

I'm working with the plugin you created and want to get the tabbed content into a template I've created.

Is there a way that I can call it to place the content in my template ?

Regards,

Matt

**Comment by JiveDig** [comment]
I'm guessing you got it?

**Comment by sully1107** [comment]
Yeah, sorry had a brain wave after posting the comment.

Thank you again for the plugin.

**Comment by JiveDig** [comment]
Glad you like it. I hope to make a new version that is a custom block, and removes jQuery... at some point.
